### ISSUE TITLE
Update font sizes for mobile displays

### ISSUE THREAD

**Issue by joeytepp** [qhacks/qhacks-website#119]
## Summary
The generic font sizes in our stylesheet do not match the mocks on mobile displays. Although Zeplin says that they are the same size, it is evident that they are not from the word wrapping on mobile displays on [dev.qhacks.io](https://dev.qhacks.io). The stylesheet should be updated so that font size changes accordingly for mobile and smaller displays

### Basic Example

`index.css`
```css
h1: {
  font-size: 20px
  ...
}
@media (max-width: 800px) {
  h1: {
    font-size: 1.5em
    ...
  }

}
```
